format_version: 10
pipelines:
  blog-build:
    group: ztec.fr
    materials:
      blog-ztec:
        git: ssh://git@git.riper.fr:22023/ztec/blog.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            build:
              timeout: 0
              resources:
                - hugo
              tasks:
                - exec:
                    arguments:
                      - -c
                      - docker build -t git2.riper.fr/ztec/blog:$GO_PIPELINE_LABEL .
                    command: /bin/bash
                    run_if: passed
              artifacts:
              - external:
                  id: blog-img
                  store_id: ztec
                  configuration:
                    options:
                      Image: git2.riper.fr/ztec/blog
                      Tag: ${GO_PIPELINE_LABEL}
  blog-deploy:
    group: ztec.fr
    materials:
      blog-build:
        ignore_for_scheduling: false
        pipeline: blog-build
        stage: build
      blog-ztec:
        git: ssh://git@git.riper.fr:22023/ztec/blog.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            helm-update:
              timeout: 0
              resources:
                - docker
                - kubectl
              tasks:
                - fetch:
                    artifact_id: blog-img
                    pipeline: blog-build
                    stage: build
                    job: build
                    artifact_origin: external
                    run_if: passed
                - exec:
                    arguments:
                      - -c
                      - helm3 upgrade --wait --install --set-string image.name="$ARTIFACT_IMAGE" blog ./helm -f helm/values.yaml --wait
                    command: /bin/bash
                    run_if: passed