apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blog-resources
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: pv-blog-resources
  storageClassName: trantor-nfs
