apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blog-public
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: pv-blog-public
  storageClassName: trantor-nfs
