apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app }}"
  labels:
    app: {{ .Values.app }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: git2.riper.fr-key
      containers:
        - name: {{ .Release.Name }}
          image: "{{ required "image.name is required, specify it with --set-string image.nametoto:label" .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}

