on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:

      - name: "Manual checkout"
        run: |
          cat >~/.ssh/id_rsa <<STRING
          ${{ secrets.GIT_SSH_KEY }}
          STRING
          chmod 0700 ~/.ssh/id_rsa
          GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o CheckHostIP=no' git clone ssh://git@git.riper.fr:22023/ztec/blog.git 
          cd blog
          git submodule update --init --recursive
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: git2.riper.fr
          username: ${{ vars.DOCKER_LOGIN }}
          password: ${{ vars.DOCKER_TOKEN }}
      - name: Docker build
        run: docker buildx build -t git2.riper.fr/ztec/blog:${{ github.ref_name }}-${{ github.run_id }} blog
      - name: Docker push
        run: docker push git2.riper.fr/ztec/blog:${{ github.ref_name }}-${{ github.run_id }}
  Deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          path: code
      - name: checkout prod branch
        uses: actions/checkout@v4
        with:
          path: prod
          ref: 'prod'
      - name: "prepare deployment"
        run: |
          cat <<EOF > ./kustomization.yaml
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - code/k8s/
          images:
            - name: git2.riper.fr/ztec/blog
              newName: git2.riper.fr/ztec/blog
              newTag: "${{ github.ref_name }}-${{ github.run_id }}"
          EOF
      - name: "generate resources"
        uses: https://github.com/steebchen/kubectl@v2.0.0
        with:
          version: v1.27.15
          config: ${{ vars.KUBE_CONFIG_TRANTOR }}
          command: kustomize ./ -o prod/
      - name: "commit and push manifests"
        run: |
            cd prod
            git config --global user.name "Butler"
            git config --global user.email "butler[bot]@riper.fr"
            git add *
            git commit -m "Deploy blog:${{ github.ref_name }}-${{ github.run_id }}" || echo "No changes to commit"
            git push --force origin prod

  Clear-CDN:
    runs-on: ubuntu-24.04
    needs: Deploy
    steps:
      - name: Wait for deployment to settle
        run: sleep 60
      - name: Clear image cache
        run: |
          set -e
          curl --fail --request POST \
          --url https://api.bunny.net/pullzone/4889935/purgeCache \
          --header 'AccessKey: ${{ secrets.BUNNY_API_KEY }}' \
          --header 'accept: application/json' \
          --header 'content-type: application/json' \
          --data '{"CacheTag": "*page*"}'